language: python
python:
    - "3.3"
    - "3.4"
install:
    - "pip install -r requirements.txt"
script:
    - "flake8 ."
    - "PYTHONPATH=$PYTHONPATH:. py.test tests"
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.4"
        repo: "pyvec/python.cz"
